apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{template "fullname" .}}-lnd-provision-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{template "fullname" .}}-lnd-update-secrets-role
  namespace: default
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "create", "watch", "update", "patch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{template "fullname" .}}-lnd-update-secrets-role-binding
  namespace: default
roleRef:
  kind: Role
  name: {{template "fullname" .}}-lnd-update-secrets-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{template "fullname" .}}-lnd-provision-account
    namespace: default