---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{template "debugger.fullname" .}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{template "debugger.fullname" .}}
  template:
    metadata:
      labels:
        app: {{template "debugger.fullname" .}}
    spec:
      containers:
      - name: {{template "debugger.fullname" .}}
        image: debian:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: lnd-alice-pvc
          mountPath: /root/alice.lnd
        - name: lnd-bob-pvc
          mountPath: /root/bob.lnd  
        - name: shared-pvc
          mountPath: /rpc
        - name: btcd-pvc
          mountPath: /data
        - name: secret-volume-alice
          mountPath: /tmp/secret-volume-alice
        - name: secret-volume-bob
          mountPath: /tmp/secret-volume-bob
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: lnd-alice-pvc
        persistentVolumeClaim:
          claimName: {{template "alice.fullname" .}}-pvc
      - name: shared-pvc
        persistentVolumeClaim:
          claimName: {{template "fullname" .}}-shared-pvc
      - name: lnd-bob-pvc
        persistentVolumeClaim:
          claimName: {{template "bob.fullname" .}}-pvc
      - name: btcd-pvc
        persistentVolumeClaim:
          claimName: {{template "btcd.fullname" .}}-pvc
      - name: secret-volume-alice
        secret:
          secretName: {{template "alice.fullname" .}}-wallet-secret
      - name: secret-volume-bob
        secret:
          secretName: {{template "bob.fullname" .}}-wallet-secret
      - name: prometheus-config
        configMap:
          name: {{template "prometheus.fullname" .}}-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: {{template "prometheus.fullname" .}}-pvc
      - name: grafana-datasources
        configMap:
          name: {{template "grafana.fullname" .}}-config-datasources
      - name: grafana-dashboards
        persistentVolumeClaim:
          claimName: {{template "grafana.fullname" .}}-dashboards-pvc
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: {{template "grafana.fullname" .}}-pvc

