---
apiVersion: v1
kind: Service
metadata:
  name: {{template "grafana.fullname" .}}-svc
spec:
  selector:
    app: {{template "grafana.fullname" .}}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
