---
apiVersion: v1
kind: Service
metadata:
  name: {{template "bob.fullname" .}}-lndmon-svc
spec:
  selector:
    app: {{template "bob.fullname" .}}-lndmon
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
