---
apiVersion: v1
kind: Service
metadata:
  name: {{template "bob.fullname" .}}-prometheus-svc
spec:
  selector:
    app: {{template "bob.fullname" .}}-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090