---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "btcd.fullname" .}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.btcd.pvc.size }}