---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "grafana.fullname" .}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.pvc.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "grafana.fullname" .}}-dashboards-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.dashboards.pvc.size }}
