---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "bob.fullname" .}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bob.pvc.size }}
