---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "prometheus.fullname" .}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.pvc.size }}
