---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "alice.fullname" .}}-prometheus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.pvc.size }}
