---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{template "fullname" .}}-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.shared.pvc.size }}