---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "grafana.fullname" .}}-config-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Bob-Prometheus
        type: prometheus
        access: proxy
        url: http://{{template "bob.fullname" .}}-prometheus-svc:9090
        editable: true
      - name: Alice-Prometheus
        type: prometheus
        access: proxy
        url: http://{{template "alice.fullname" .}}-prometheus-svc:9090
        editable: true
