---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "grafana.fullname" .}}-config-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{template "prometheus.fullname" .}}-svc:9090
        editable: true
